name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - uses: actions/cache@v2
        with:
          path: .yarn/.cache
          key: v1-cache
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn type-check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .pnp.js
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - uses: actions/cache@v2
        with:
          path: .yarn/.cache
          key: v1-cache
      - name: Build
        run: yarn build:ci
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          AUTH_ROOT: ${{ secrets.AUTH_ROOT }}
          AUTH_PROXY: ${{ secrets.AUTH_PROXY }}
          API_ROOT: ${{ secrets.API_ROOT }}
          WS_ROOT: ${{ secrets.WS_ROOT }}
          SEA_URL: ${{ secrets.SEA_URL }}
